### ISSUE TITLE
[Bug] (dev) plex_login 504

### ISSUE THREAD

**Issue by lukepolo** [petio-team/petio#474]
**Describe the bug**
When trying to login through either form or plex oauth , `plex_login` request timed out.

**To Reproduce**
1. Try to login, look at network request.

**Expected behavior**
Request should return a 200. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2066668/123116295-c6827080-d40e-11eb-87a6-d9c888e45d2d.png)

**Desktop (please complete the following information):**
 - OS: osx
 - Browser chrome

**Comment by ADRFranklin** [comment]
This seems to be a problem at plex's side, I have just checked this after having the same issue yesterday and it seems to have solved itself. 

Could you double check and make sure it's still happening your side?

**Comment by lukepolo** [comment]
Looks to be still broken , I reverted to the `latest` and seems to work though.

**Comment by ADRFranklin** [comment]
I'm unable to reproduce this my end now, could you please try again and clear your cache.

**Comment by ADRFranklin** [comment]
To make 100% sure, try logging in, in a private browser, as this won't be affected by cache.

**Comment by lukepolo** [comment]
Tried 2 different browsers, both incognito. Tried an entire different device as well. I’ll check the docker logs for anything useful.

**Comment by hbooo** [comment]
If it can help, here is my docker logs for the same error : 
`(node:228) UnhandledPromiseRejectionWarning: TypeError: getClientIp is not a function
at /app/api/routes/login.js:158:22
at Layer.handle [as handle_request] (/app/api/node_modules/express/lib/router/layer.js:95:5)
at next (/app/api/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/app/api/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/app/api/node_modules/express/lib/router/layer.js:95:5)
at /app/api/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/app/api/node_modules/express/lib/router/index.js:335:12)
at next (/app/api/node_modules/express/lib/router/index.js:275:10)
at Function.handle (/app/api/node_modules/express/lib/router/index.js:174:3)
at router (/app/api/node_modules/express/lib/router/index.js:47:12)
at Layer.handle [as handle_request] (/app/api/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/app/api/node_modules/express/lib/router/index.js:317:13)
at /app/api/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/app/api/node_modules/express/lib/router/index.js:335:12)
at next (/app/api/node_modules/express/lib/router/index.js:275:10)
at /app/api/app.js:123:9
at Layer.handle [as handle_request] (/app/api/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/app/api/node_modules/express/lib/router/index.js:317:13)
at /app/api/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/app/api/node_modules/express/lib/router/index.js:335:12)
at next (/app/api/node_modules/express/lib/router/index.js:275:10)
at cookieParser (/app/api/node_modules/cookie-parser/index.js:57:14)
(node:228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

2021-06-24 00:39:34 [31merror[39m: [HPM] Error occurred while proxying request 192.168.1.96:7777/login to http://localhost:7778/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
`

**Comment by ADRFranklin** [comment]
hmm, I added this function recently and didn't get any issues my side while testing, though I am about to remove this function in favour of a different method that uses express to handle the proxies, so after I push that, this should fix that issue.

**Comment by lukepolo** [comment]
Nice it fixed it!
